# Generated by Django 4.1.2 on 2022-10-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('KZ', 'KAZARMU'), ('FD', 'FIELD'), ('OUT', 'OUTSIDE')], default='KZ', max_length=32),
        ),
    ]
